## Stepik - Интерактивный тренажер по SQL

In [1]:
import pandas as pd 
from sqlalchemy import create_engine


engine = create_engine(
    "postgresql://postgres:Alex84032623354!@localhost:5432/postgres"
)

df = pd.read_sql("SELECT * FROM book", engine)
df

,book_id,title,author,price,amount,buy,genre_id,author_id
0,3,Идиот,Достоевский Ф.М.,326.05,22,0,1,2
1,4,Братья Карамазовы,Достоевский Ф.М.,453.04,3,0,1,2
2,5,Игрок,Достоевский Ф.М.,283.73,10,0,1,2
3,10,Анна Каренина,Толстой Л.Н.,533.17,15,0,1,9
4,1,Мастер и Маргарита,Булгаков М.А.,380.45,3,0,1,1
5,7,Евгений Онегин,Пушкин А.С.,360.20,10,0,2,3
6,8,Лирика,Пастернак Б.Л.,373.62,10,0,2,4
7,2,Белая гвардия,Булгаков М.А.,474.90,33,0,3,2
8,9,Война и мир,Толстой Л.Н.,770.44,10,0,1,9
9,6,Стихотворения и поэмы,Есенин С.А.,526.50,15,0,2,3
10,11,Черный человек,Есенин С.А.,500.99,30,0,3,3

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   book_id    11 non-null     int64
 1   title      11 non-null     object
 2   author     11 non-null     object
 3   price      11 non-null     float64
 4   amount     11 non-null     int64
 5   buy        11 non-null     int64
 6   genre_id   11 non-null     int64
 7   author_id  11 non-null     int64
dtypes: float64(1), int64(5), object(2)
memory usage: 836.0+ bytes

In [3]:
df.describe()

         book_id       price     amount   buy   genre_id  author_id
count  11.000000   11.000000  11.000000  11.0  11.000000  11.000000
mean    6.000000  453.008182  14.636364   0.0   1.636364   3.636364
std     3.316625  134.285310   9.922426   0.0   0.809040   2.766685
min     1.000000  283.730000   3.000000   0.0   1.000000   1.000000
25%     3.500000  366.910000  10.000000   0.0   1.000000   2.000000
50%     6.000000  453.040000  10.000000   0.0   1.000000   3.000000
75%     8.500000  513.745000  18.500000   0.0   2.000000   3.500000
max    11.000000  770.440000  33.000000   0.0   3.000000   9.000000

In [4]:
df2 = pd.read_sql("""SELECT
    title,
    author,
    amount,
    (SELECT MAX(amount) FROM book) - amount AS Заказ
FROM book
WHERE amount < (SELECT MAX(amount) FROM book)""", engine)       
df2 # Вывести название книги, автора, количество экземпляров в наличии и 
# сколько нужно заказать до максимального количества экземпляров
# для всех книг, у которых количество экземпляров меньше максимального
#  количества экземпляров среди всех книг

                   title            author  amount  Заказ
0                  Идиот  Достоевский Ф.М.      22     11
1      Братья Карамазовы  Достоевский Ф.М.       3     30
2                  Игрок  Достоевский Ф.М.      10     23
3          Анна Каренина      Толстой Л.Н.      15     18
4     Мастер и Маргарита     Булгаков М.А.       3     30
5         Евгений Онегин       Пушкин А.С.      10     23
6                 Лирика    Пастернак Б.Л.      10     23
7            Война и мир      Толстой Л.Н.      10     23
8  Стихотворения и поэмы       Есенин С.А.      15     18
9         Черный человек       Есенин С.А.      30      3

In [5]:
df1 = pd.read_sql("""SELECT author, title, price
FROM book
WHERE price <= (
    SELECT AVG(price)
    FROM book)
ORDER BY price DESC""", engine)
df1 # Вывести автора, название и цену всех книг, цена которых меньше
#  или равна средней цене всех книг, отсортировав результат по убыванию цены

             author               title   price
0     Булгаков М.А.  Мастер и Маргарита  380.45
1    Пастернак Б.Л.              Лирика  373.62
2       Пушкин А.С.      Евгений Онегин  360.20
3  Достоевский Ф.М.               Идиот  326.05
4  Достоевский Ф.М.               Игрок  283.73